### ISSUE TITLE
Failed to load the linter-gcc package

### ISSUE THREAD

**Issue by WelderFernandes** [AtomLinter/linter-gcc#118]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [linter-gcc](https://github.com/hebaishi/linter-gcc) package 0.7.1

### Stack Trace

Failed to load the linter-gcc package

```
At Cannot find module 'tempfile'

Error: Cannot find module 'tempfile'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:/Program Files (x86)/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/linter-gcc-master/lib/main.js:103:12)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at /app.asar/src/package.js:123:28
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at Package.module.exports.Package.load (/app.asar/src/package.js:110:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/app.asar/src/package-manager.js:468:14)
    at /app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/app.asar/src/package-manager.js:407:19)
    at /app.asar/src/atom-environment.js:792:28
```

### Commands

```
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
atom-material-ui 1.3.9 
script 3.14.1 
aurora-theme 1.2.2 
keymaps undefined 
lib undefined 
linter-gcc 0.7.1 
menus undefined 
resources undefined 
spec undefined 
styles undefined 
```

**Comment by LearnToStick** [comment]
I also encountered this error， how to repair this error？

**Comment by hebaishi** [comment]
Github decided to sunset Atom on December 15 2022 (you can read more about that [here](https://github.blog/2022-06-08-sunsetting-atom/). I will take steps to archive this repository, as it is deprecated code by extension.
